# Generated by Django 4.0.4 on 2022-04-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSlot',
        ),
    ]
