# Generated by Django 4.0.4 on 2022-04-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userslot',
            old_name='user_id',
            new_name='user',
        ),
    ]
